#!/usr/bin/perl -w
#
#

use strict;
use DBI;
use Mail::Sendmail;

my $DB    = 'econsulter';
my $dbh   = DBI->connect("dbi:Pg:dbname=$DB;host=192.168.1.3", 'e-consulter', 'c3p+#') or die (DBI->errstr);

my $day   = (localtime)[3];
my $month = (localtime)[4] + 1;
my $year  = (localtime)[5] + 1900;


my $recipients_ref = $dbh->selectall_arrayref("
  SELECT ben_email
    FROM benutzer
   WHERE ben_admin
     AND ben_email <> ''
     AND ben_email IS NOT NULL");

my $birthdays_ref = $dbh->selectall_arrayref("
  SELECT ben_nachname, ben_vorname, ben_email, ben_gebdat
    FROM benutzer
   WHERE date_part('month', ben_gebdat) = '$month'
     AND date_part('day', ben_gebdat) = '$day'
  ORDER BY ben_nachname");



if ($#{$birthdays_ref} != -1) {
  my @recipients;
  my $mailtext = <<EOF;
Hallo,

hier ist der freundliche Geburtstagserinnerungsdienst des e-consulters.
Folgende Personen haben heute Geburtstag:


EOF


  foreach (@$recipients_ref) {
    push(@recipients, $$_[0]);
  }


  foreach (@$birthdays_ref) {
    my ($nachname, $vorname, $email, $gebdat) = @$_;
    $gebdat =~ /^(\d+)-\d+-\d+$/;
    my $age = $year - $1;

    $mailtext .= sprintf(" %-61s%s [%s]\n", "$nachname, $vorname ($email)", $gebdat, $age);
  }

  $mailtext .= "\n\nMit freundlichen Gruessen,\ne-consulter";


  sendmail( To      => join(',', @recipients),
            From    => 'birthday_reminder@e-consulter.com',
            Subject => sprintf("Geburtstage %d-%02d-%02d", $year, $month, $day),
            Message => $mailtext) or die ($Mail::Sendmail::error);
}

$dbh->disconnect;

