--
-- PostgreSQL database dump
--

-- SET client_encoding = 'SQL_ASCII';
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;

--
-- Data for Name: translate; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO translate (lfdnr, n, de, en) VALUES (1, 0, 'Firma', 'company');
INSERT INTO translate (lfdnr, n, de, en) VALUES (2, 0, 'Wenn Sie mehr über unser Datensicherheitskonzept wissen möchten, kontaktieren Sie uns unter <a href=''mailto:virtualassessment@e-consulter.de''>virtualassessment@e-consulter.de</a>. Wir beantworten gerne Ihre Fragen.', 'If you want more information about our data security system, please contact us at <a href=''mailto:virtualassessment@e-consulter.de''>virtualassessment@e-consulter.de</a>. We''ll be happy to answer your questions.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (3, 0, 'Willkommen in unserem virtuellen Assessment-Center. Zu Beginn finden Sie eine kurze Einführung mit Informationen über den Ablauf und das Auswertungsverfahren. Wir sichern Ihnen hiermit rechtsverbindlich zu, dass alle Ihre Angaben vertraulich behandelt werden. Nach der Bearbeitung der Aufgaben entscheiden Sie persönlich, ob Sie Ihre Testergebnisse an uns weitergeben.', 'Welcome to our virtual assessment center. First you will find a short introduction describing the asssessment process and method. We give you our legally binding assurance that all of your information is treated confidentially. After completing the different assessment sections, it''s up to you whether you want to share your test scores with us or not. ');
INSERT INTO translate (lfdnr, n, de, en) VALUES (4, 0, 'Bitte bearbeiten Sie die folgenden Aufgaben so zügig wie möglich, ohne lange zu überlegen. Bei der Bearbeitung der folgenden Aufgaben und Fragen gibt es keine "richtigen" oder "falschen" Antworten oder Entscheidungen.', 'Please complete the tasks in the following sections as quickly as possible without thinking too long about your answers. There is no such thing as a "right" or "wrong" answer or decision in the following sections. ');
INSERT INTO translate (lfdnr, n, de, en) VALUES (5, 0, 'Die Bearbeitung der Postkorbübung dauert ca. 25 Minuten.', 'The in-box exercise will take approximately 25 minutes.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (6, 0, 'Die Bearbeitung des Fragebogens dauert ca. 15 Minuten.', 'Answering the questionnaire will take about 15 minutes. ');
INSERT INTO translate (lfdnr, n, de, en) VALUES (7, 0, 'Folgende Aufgaben liegen vor Ihnen:', 'You are asked to complete the following: ');
INSERT INTO translate (lfdnr, n, de, en) VALUES (8, 0, 'Fragebogen', 'Questionnaire');
INSERT INTO translate (lfdnr, n, de, en) VALUES (9, 0, 'Postkorb', 'In-box exercise ');
INSERT INTO translate (lfdnr, n, de, en) VALUES (10, 0, 'Willkommen', 'Welcome ');
INSERT INTO translate (lfdnr, n, de, en) VALUES (11, 0, 'Projekt', 'project');
INSERT INTO translate (lfdnr, n, de, en) VALUES (12, 0, 'Telefon', 'telephone');
INSERT INTO translate (lfdnr, n, de, en) VALUES (13, 0, 'Anleitung', 'guide');
INSERT INTO translate (lfdnr, n, de, en) VALUES (14, 0, 'Einführung', 'Introduction');
INSERT INTO translate (lfdnr, n, de, en) VALUES (15, 0, 'Der Fragebogen', 'Questionnaire');
INSERT INTO translate (lfdnr, n, de, en) VALUES (16, 0, 'Der Fragebogen zur "Persönlichen Selbsteinschätzung" besteht aus 40 Fragen. Nach Beendigung des Fragebogens erhalten Sie eine detaillierte Auswertung mit Erläuterungen und Vergleichsstichproben.', 'The "personal self-assessment" questionnaire consists of 40 questions. After completing the questionnaire, you will receive a detailed evalution that includes explanations and relative data samples.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (45, 0, 'Menschen mit höheren Extraversionswerten beschreiben sich häufig als aktiv und energievoll. Sie neigen zu einem eher heiteren Naturell. Extrovertierte fühlen sich in Gruppen und auf gesellschaftlichen Versammlungen besonders wohl. Es fällt ihnen auch leicht, sich in sozialen Situationen durchzusetzen.', 'People with a high score in extraversion often describe themselves as active, high energy people. They also tend to be cheerful. Extroverts particularly like being in groups and taking part in social events. It is also easy for them to take a lead in social situations.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (17, 0, 'Bitte beantworten Sie die folgenden Fragen so wahrheitsgemäß wie möglich.', 'Please answer the following questions as honestly as possible.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (46, 0, 'Introversion wird in der psychologischen Fachliteratur dagegen eher als ein Fehlen der Extraversion gesehen, nicht als ein Gegensatz zu ihr. Introvertierte sind demnach eher zurückhaltend als ängstlich, eher unabhängig als folgsam.', 'According to psychological research, introversion is seen more as an absence of extraversion rather than its opposite. Hence, introverts are more reserved than anxious, more independent than docile.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (47, 0, 'Introvertierte Menschen verspüren keine soziale Ängstlichkeit, sondern eher den bewussten Wunsch, allein zu sein. Sie sind keinesfalls pessimistisch oder unglücklich, auch wenn die überschäumende Lebhaftigkeit und Begeisterungsfähigkeit extrovertierter Menschen ihnen fremd sind.', 'Introverts do not feel anxiety in social situations, but rather have a conscious desire to be alone. Although they are not familiar with the vivacity and enthusiasm of extroverts, they are by no means pessimistic or unhappy.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (18, 0, 'Einführung Fragebogen', 'Introduction into questionnaire');
INSERT INTO translate (lfdnr, n, de, en) VALUES (19, 0, 'Bedenken Sie immer, dass es bei der Beantwortung keine "richtigen" oder falschen" Antworten gibt. Es geht jeweils um Ihre ganz persönliche, subjektive Selbsteinschätzung.', 'You should always keep in mind that there are no "right" or "wrong" answers to the questions in this questionnaire.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (20, 0, 'Unser Fragebogen basiert auf dem von der psychologischen Forschung entwickelten sogenannten "Fünf-Faktoren-Modell", das die folgenden fünf Persönlichkeitsaspekte unterscheidet: Neurotizismus, Extraversion, Gewissenhaftigkeit, Motivation, Soziale Kompetenz. Zu allen fünf Aspekten finden Sie nähere Erläuterungen unter dem jeweiligen Menüpunkt.', 'Our questionnaire is based on the so-called five factors model developed in psychological research which identifies the following five personality traits: neuroticism, extraversion, conscientiousness, motivation, and social competence. For detailed information on each of these five traits please refer to the respective menu item.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (48, 0, 'Introvertierte Menschen wählen daher meist Tätigkeiten, die weniger mit anderen Menschen zu tun haben. Sie arbeiten gerne selbständig oder in kleinen Teams.', 'As a  result, introverts choose activities which do not involve much contact with other people. They like to work by themselves or in small teams.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (49, 0, 'Gewissenhaftigkeit', 'Conscientiousness');
INSERT INTO translate (lfdnr, n, de, en) VALUES (21, 0, 'Insgesamt umfasst der Fragebogen 40 Aussagen, die sich zur Beschreibung Ihrer Persönlichkeit eignen könnten. Lesen Sie bitte jede Aussage aufmerksam durch und entscheiden Sie spontan, ob Sie der jeweiligen Aussage zustimmen oder nicht.', 'The entire questionnaire consists of 40 statements which are used for describing your personality. Please read each statement carefully and decide whether you agree with the respective statement or not without thinking too long about your answer.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (22, 0, 'Zur Beantwortung steht Ihnen eine Skala von starker Ablehnung (0%) bis starker Zustimmung (100%) zur Verfügung.', 'The scale for your answers ranges from strong strongly disagree (0%) to strongly agree (100%).');
INSERT INTO translate (lfdnr, n, de, en) VALUES (23, 0, 'In dem folgenden Online-Fragebogen erhalten Sie pro Seite 5 Fragen. Solange Sie eine Seite bearbeiten, können Sie auch Änderungen in Ihren Antworten vornehmen. Erst wenn Sie alle Fragen auf der Seite beantwortet haben und auf "weiter" klicken, speichert das Programm Ihre Antworten und wechselt automatisch zur nächsten Seite.', 'The following online questionnaire contains five questions per page. While you are still working on one page, you are free to modify your answers. Only after you have finished all the questions on that page and clicked on the "continue" button, will your answers be saved and you will automatically be brought to the next page.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (24, 0, 'Frage', 'Question');
INSERT INTO translate (lfdnr, n, de, en) VALUES (25, 0, 'Im Rahmen des Fragebogens wurden die bereits erwähnten fünf Persönlichkeitsfaktoren abgefragt und bewertet. Sie erhalten nun Ihr persönliches Testergebnis. Um weitere Informationen bezüglich der einzelnen Auswertungsbereiche zu erhalten, wählen Sie die entsprechenden Menüpunkte. In einer zweiten Auswertung erhalten Sie Angaben zu einer repräsentativen Stichprobe. Für weitergehende Fragen stehen wir Ihnen unter: <a href=''mailto:virtualassessment@e-consulter.de''>virtualassessment@e-consulter.de</a> zur Verfügung. Vielen Dank für Ihr Interesse!', 'In this questionniare, the five personality traits  mentioned above were tested and evaluated. You will now receive your personal test scores. For further information regarding the different assessment categories, please refer to the respective menu item. In a second evaluation, we will provide representative data samples. If you have any further questions please contact us at <a href=''mailto:virtualassessment@e-consulter.de''>virtualassessment@e-consulter.de</a>. Thank you very much for your interest.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (26, 0, 'Ihr Ergebnis', 'Your test scores');
INSERT INTO translate (lfdnr, n, de, en) VALUES (27, 0, 'Referenz', 'Reference data');
INSERT INTO translate (lfdnr, n, de, en) VALUES (28, 0, 'Ergebnis', 'Test scores');
INSERT INTO translate (lfdnr, n, de, en) VALUES (29, 0, 'Kennung', 'Username');
INSERT INTO translate (lfdnr, n, de, en) VALUES (30, 0, 'Passwort', 'Password');
INSERT INTO translate (lfdnr, n, de, en) VALUES (31, 0, 'Anmelden', 'Sign in');
INSERT INTO translate (lfdnr, n, de, en) VALUES (32, 0, 'Sehr geehrter Herr', 'Dear Mr');
INSERT INTO translate (lfdnr, n, de, en) VALUES (33, 0, 'Sehr geehrte Frau', 'Dear Ms');
INSERT INTO translate (lfdnr, n, de, en) VALUES (34, 0, 'Die Auswertung Ihres Fragebogens liefert Ihnen inen ersten Eindruck von Ihren persönlichen Arbeitspräferenzen. Sie kann Ihnen dazu dienen, gemeinsam mit uns Ihre persönliche Rolle und Aufgabe in unseren Projektteams zu finden.', 'The evaluation of your questionnaire will provide a rough idea of your personal work preferences. The results will help you work with us to find your personal role and area of responsibility in our project teams.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (35, 0, 'Sollten Sie sich persönlich überhaupt nicht in den Auswertungsergebnissen wiederfinden oder haben  Sie andere Rückfragen, wenden Sie sich vertrauensvoll an <a href=''mailto:virtualassessment@e-consulter.de''>virtualassessment@e-consulter.de</a>.', 'Should you be extremely unhappy with the results of the evaluation or have further questions, you can send your questions to us at <a href=''mailto:virtualassessment@e-consulter.de''>virtualassessment@e-consulter.de</a>.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (36, 0, 'Auf den folgenden Seiten erhalten Sie die Auswertung zu den fünf Persönlichkeitsfaktoren, die der von Ihnen bearbeitete Fragebogen erfasst.', 'The five personality trait results evaluated by the questionnaire are shown on the following pages.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (37, 0, 'Erläuterung', 'Explanation');
INSERT INTO translate (lfdnr, n, de, en) VALUES (38, 0, 'Neurotizismus', 'Neuroticism');
INSERT INTO translate (lfdnr, n, de, en) VALUES (39, 0, 'Die Dimension Neurotizismus erfasst individuelle Unterschiede bezüglich der emotionalen Stabilität bzw. emotionalen Instabilität einer Person.', 'Neuroticism includes individual differences with respect to a person''s emotional stability or instability.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (40, 0, 'Menschen mit niedrigen Neurotizismuswerten beschreiben sich eher als ruhig, ausgeglichen und sorgenfrei. Sie sind emotional stabil und lassen sich daher auch in Stresssituationen nicht so schnell aus der Fassung bringen.', 'People with a low score often describe themselves as calm, balanced and carefree. They are emotionally stable and, as a result, hardly ever lose their self-control even in stressful situations.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (41, 0, 'Menschen mit hohen Neurotizismuswerten beschreiben sich eher als ängstlich, traurig und unsicher. Menschen mit dieser persönlichen Ausprägung geben außerdem häufig an, leichter aus dem emotionalen Gleichgewicht gebracht zu werden. Stressige Situationen, problembehaftete Aufgabenstellungen oder Entscheidungen in Zeiten der Unsicherheit werden meist als bedrohlich und beängstigend empfunden.', 'People with a high score in neuroticism often describe themselves as anxious, sad, and insecure. In addition, these people say that it is fairly easy to upset their emotional balance. Stressful situations, tasks with lots of problems or decisions that must be made in times of incertainty are generally perceived as threatening or frightening.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (42, 0, 'Menschen mit hohen Neurotizismuswerten wählen aus diesen Gründen eher Tätigkeiten, die weniger zeitkritisch und stressbehaftet sind bzw. die weniger kritische Herausforderungen stellen.', 'Hence people with a high score tend to choose activities which are less time-sensitive and stressful or which involve less critical challenges.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (43, 0, 'Extraversion', 'Extraversion');
INSERT INTO translate (lfdnr, n, de, en) VALUES (44, 0, 'Extrovertierte Menschen sind beruflich häufig in leitenden Positionen oder im Vertrieb tätig. Neue Herausforderungen und Aufgaben begeistern sie; mit ganzer Kraft setzen sie sich für Innovationen ein. Eigenschaften wie Dominanz, Selbstbejahung, Geselligkeit, soziales Auftreten und Fähigkeit zum Erfolg sind bei ihnen besonders häufig zu finden.', 'Extroverts often have jobs in leadership positions or in sales and marketing. They are excited by new challenges and assignments; they put all their energy in innovative solutions. Extroverts generally exhibit dominance, self-confidence, conviviality, good social skills and a talent for success.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (50, 0, 'Der Auswertungsbereich "Gewissenhaftigkeit" bezieht sich auf den aktiven Prozess der Planung, Organisation, Gestaltung und Durchführung von Aufgaben. Der besondere Aspekt dieser Dimension liegt in der engen Verbindung zu beruflichen oder akademischen Leistungen. Menschen mit höheren Punktwerten in diesem Auswertungsbereich beschreiben sich meist als zielstrebig, systematisch, ausdauernd, fleißig, genau und willensstark. Personen, die hier niedrige Werte erzielen, haben ein eher niedriges Anspruchsniveau an ihre beruflichen Leistungen und sind daher in ihrer Arbeit häufig nachlässig und unbeständig. Extreme Punktwerte im Bereich "Gewissenhaftigkeit" können jedoch negative Erscheinungsbilder mit sich bringen, wie etwa Arbeitssucht, übertrieben hohes Anspruchsniveau oder zwanghafte Ordnungssucht.', '"Conscientiousness" refers to the active process of planning, organization, and execution of assignments. This trait is special because it is closely connected to professional or academic achievements. People with a high score in this assessment category generally describe themselves as goal-orientated, systematic, persevering, hard-working, accurate and strong-minded. People with a low score in this category have somewhat low standards in their professional activities and are, as a result, somewhat careless and inconsistent in their work. It has to be said, though, that an extremely high score in this category can have negative implications such as being a workoholic, having unreasonable standards or being compulsive about order.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (51, 0, 'Motivation - Stresstoleranz', 'Motivation / stress tolerance');
INSERT INTO translate (lfdnr, n, de, en) VALUES (52, 0, 'Die Dimension "Motivation/Stresstoleranz" ist mit der Dimension "Gewissenhaftigkeit" eng verbunden.', 'The dimension "motivation / stress tolerance" is closely connected to "conscientiousness".');
INSERT INTO translate (lfdnr, n, de, en) VALUES (53, 0, 'Menschen mit hohen Punktwerten zeichnen sich in der Regel durch einen gesunden Optimismus aus, der es ihnen ermöglicht, ihre Ziele und Aufgaben beharrlich zu verfolgen, Hindernissen und Rückschlägen zum Trotz. Diese Menschen zeigen meist auch eine größere Eigeninitiative, wenn es darum geht, Chancen nicht nur zu sehen, sondern auch zu ergreifen und zu nutzen. Des Weiteren ist eine höhere Leistungsmotivation zu nennen, gesetzte Ziele zu erreichen oder zu übertreffen. Personen mit hohen Punktwerten im Bereich "Motivation" verstehen es auch meist sehr gut, innerhalb eines Teams oder einer Gruppe Engagement zu zeigen und die Zusammenarbeit aller Teammitglieder zum Erreichen gemeinsamer Ziele zu fördern.', 'People with a high score in this category are usually characterized by a healthy optimism which enables them to persevere in their goals and tasks even in the face of obstacles and setbacks. These people generally take initiative not just when it comes to  perceiving opportunities, but also seizing and making use of them. Moreover, they are more highly motivated to achieve or exceed set goals. People with a high score in the "motivation" category also demonstrate more commitment within a team or a group and promote co-operation among all team members to achieve mutual goals.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (54, 0, 'Soziale Kompetenz', 'Social competence');
INSERT INTO translate (lfdnr, n, de, en) VALUES (55, 0, 'In vielen wissenschaftlichen Definitionen ist die Dimension "soziale Kompetenz" sehr weit gefasst. Im Rahmen dieses Fragebogens bezieht sich diese Dimension jedoch hauptsächlich auf den Aspekt der Teamfähigkeit. Menschen mit hoher sozialer Kompetenz sind in der Lage, andere Teammitglieder leicht zu verstehen und so die Vielfalt der verschiedenen Charaktere als Chance zur Erreichung der Teamziele zu nutzen. Hinzu kommt meist eine sehr ausgeprägte Fähigkeit zur Konfliktbewältigung, wie z.B. unvoreingenommen über Meinungsverschiedenheiten diskutieren zu können und im Team zu einer Lösung zu finden. Menschen mit hohen Punktwerten im Bereich "soziale Kompetenz" sind daher meist ausgesprochen gute Teamplayer.', 'According to many scientific definitions, "social competence" covers several different traits. For the purposes of this questionnaire, though, this trait refers mainly to being a good team-player. People with high social competence are able to understand their team members easily and are thus able to use the different personalities to accomplish the team''s goals. Most also have a marked ability to deal with conflicts, such as being able to discuss different views in an unbiased way and work out solutions within the team. People with a high score in the  "social competence" category are therefore usually very good team-players.');
INSERT INTO translate (lfdnr, n, de, en) VALUES (56, 0, 'Abmelden', 'Sign off');
INSERT INTO translate (lfdnr, n, de, en) VALUES (57, 0, 'Seite', 'page');


--
-- PostgreSQL database dump complete
--

